"use strict";(()=>{var w=Object.defineProperty;var E=(s,o,e)=>o in s?w(s,o,{enumerable:!0,configurable:!0,writable:!0,value:e}):s[o]=e;var a=(s,o,e)=>E(s,typeof o!="symbol"?o+"":o,e);var x={fr:{title:"Guide Kamea",placeholder:"D\xE9cris-moi ton besoin...",phonePlaceholder:"\u{1F4DE} Ton num\xE9ro (ex. +33 6 12 34 56 78)",phoneHint:"\u{1F4DE} Merci d'indiquer ton num\xE9ro de t\xE9l\xE9phone ci-dessous",send:"Envoyer",consent:"En discutant avec le guide, tu acceptes que ta conversation soit enregistr\xE9e pour am\xE9liorer nos r\xE9ponses. Aucune donn\xE9e marketing sans ton accord explicite.",accept:"J'accepte",addToCart:"Ajouter au panier",added:"Ajout\xE9 !",greeting:"Bonjour, je suis le guide de Kamea Nature. Quel est ton besoin aujourd'hui ?"},en:{title:"Kamea Guide",placeholder:"Tell me what you need...",phonePlaceholder:"\u{1F4DE} Your phone number (e.g. +1 555 123 4567)",phoneHint:"\u{1F4DE} Please enter your phone number below",send:"Send",consent:"By chatting with the guide, you agree that your conversation is recorded to improve our replies. No marketing data without your explicit consent.",accept:"Accept",addToCart:"Add to cart",added:"Added!",greeting:"Hi, I'm the Kamea Nature guide. What do you need today?"}};function k(){let s=navigator.language?.slice(0,2).toLowerCase();return s==="fr"?"fr":s in x?s:"fr"}function S(){let s=window.Shopify?.shop;return s?s.replace(".myshopify.com",""):"kamea-nature"}function T(){let s="kamea_advisor_session",o=localStorage.getItem(s);return o||(o=crypto.randomUUID(),localStorage.setItem(s,o)),o}async function C(s,o,e,i,t,n){let r=await fetch(s,{method:"POST",headers:{"Content-Type":"application/json",apikey:o,Authorization:`Bearer ${o}`},body:JSON.stringify({tenantSlug:e,sessionId:i,message:t})});if(!r.ok||!r.body){n.onError?.("Erreur de connexion au guide.");return}let d=r.body.getReader(),b=new TextDecoder,l="";for(;;){let{value:v,done:y}=await d.read();if(y)break;l+=b.decode(v,{stream:!0});let u;for(;(u=l.indexOf(`

`))!==-1;){let g=l.slice(0,u);l=l.slice(u+2);let f=g.match(/^event: (.+)$/m),m=g.match(/^data: (.+)$/m);if(!f||!m)continue;let p=f[1],c=JSON.parse(m[1]);p==="token"?n.onToken?.(c.text):p==="products"?n.onProducts?.(c.products):p==="handoff"?n.onHandoff?.(c.message,!!c.awaitingPhone):p==="error"?n.onError?.(c.message):p==="done"&&n.onDone?.()}}}var h=class extends HTMLElement{constructor(){super(...arguments);a(this,"sessionId","");a(this,"tenantSlug","kamea-nature");a(this,"apiUrl","");a(this,"apiKey","");a(this,"displayName",null);a(this,"locale","fr");a(this,"side","right");a(this,"vertical","bottom");a(this,"consentGiven",!1);a(this,"isOpen",!1);a(this,"messagesEl");a(this,"inputEl");a(this,"shadow");a(this,"panelEl");a(this,"launcherEl")}connectedCallback(){this.tenantSlug=this.getAttribute("tenant")??S(),this.apiUrl=this.getAttribute("api-url")??"",this.apiKey=this.getAttribute("api-key")??"",this.displayName=this.getAttribute("display-name");let[e,i]=(this.getAttribute("position")??"bottom-right").split("-");this.vertical=e==="middle"||e==="lower"?e:"bottom",this.side=i==="left"?"left":"right",this.locale=k(),this.sessionId=T(),this.consentGiven=localStorage.getItem("kamea_advisor_consent")==="1";let t=localStorage.getItem("kamea_advisor_open"),n=this.hasAttribute("auto-open");this.isOpen=t!==null?t==="1":n,this.shadow=this.attachShadow({mode:"open"}),this.render()}t(e){return x[this.locale][e]}titleText(){return this.displayName?this.locale==="fr"?`Guide ${this.displayName}`:`${this.displayName} Guide`:this.t("title")}greetingText(){return this.displayName?this.locale==="fr"?`Bonjour, je suis le guide de ${this.displayName}. Quel est ton besoin aujourd'hui ?`:`Hi, I'm the ${this.displayName} guide. What do you need today?`:this.t("greeting")}verticalCss(){return this.vertical==="middle"?"top: 50%; transform: translateY(-50%);":this.vertical==="lower"?"bottom: 30vh;":"bottom: 20px;"}render(){let e=this.shadow,i=this.side,t=this.verticalCss();e.innerHTML=`
      <style>
        :host { all: initial; }
        .launcher { position: fixed; ${t} ${i}: 20px; height: 48px; border-radius: 10px;
          background: #2b2140; color: #fff; border: none; cursor: pointer; box-shadow: 0 4px 16px rgba(0,0,0,.25);
          font-family: system-ui, sans-serif; font-size: 14px; font-weight: 600; z-index: 999999;
          display: flex; align-items: center; gap: 8px; padding: 0 16px; }
        .launcher svg { width: 20px; height: 20px; flex-shrink: 0; }
        .kamea-widget { position: fixed; ${t} ${i}: 20px; width: 340px; max-height: 480px;
          display: flex; flex-direction: column; background: #fff; border-radius: 12px;
          box-shadow: 0 8px 30px rgba(0,0,0,.18); font-family: system-ui, sans-serif; z-index: 999999; }
        .header { padding: 12px 16px; background: #2b2140; color: #fff; border-radius: 12px 12px 0 0; font-weight: 600;
          display: flex; align-items: center; justify-content: space-between; }
        .header .close { background: none; border: none; color: #fff; cursor: pointer; font-size: 18px; line-height: 1; padding: 0 0 0 8px; }
        .messages { flex: 1; overflow-y: auto; padding: 12px; display: flex; flex-direction: column; gap: 8px; min-height: 200px; max-height: 320px; }
        .msg { padding: 8px 12px; border-radius: 10px; font-size: 14px; line-height: 1.4; max-width: 85%; }
        .msg.user { align-self: flex-end; background: #2b2140; color: #fff; }
        .msg.assistant { align-self: flex-start; background: #f1eef7; color: #222; }
        .products { display: flex; flex-direction: column; gap: 6px; margin-top: 4px; }
        .product-card { border: 1px solid #eee; border-radius: 8px; padding: 8px; font-size: 13px; }
        .product-card button { margin-top: 6px; padding: 6px 10px; background: #2b2140; color: #fff; border: none; border-radius: 6px; cursor: pointer; font-size: 12px; }
        .phone-hint { display: none; padding: 8px 10px 0; font-size: 12px; font-weight: 600; color: #b45309; }
        .input-row { display: flex; gap: 6px; padding: 10px; border-top: 1px solid #eee; }
        .input-row input { flex: 1; padding: 8px; border: 1px solid #ddd; border-radius: 8px; font-size: 14px; }
        .input-row.awaiting-phone input { border: 2px solid #b45309; background: #fffbeb; }
        .input-row button { padding: 8px 12px; background: #2b2140; color: #fff; border: none; border-radius: 8px; cursor: pointer; }
        .consent { padding: 12px; font-size: 12px; color: #444; background: #f8f7fb; border-radius: 0 0 12px 12px; }
        .consent button { margin-top: 8px; padding: 6px 12px; background: #2b2140; color: #fff; border: none; border-radius: 6px; cursor: pointer; }
      </style>
      <button class="launcher" aria-label="${this.titleText()}">
        <svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.03 2 11c0 2.6 1.23 4.94 3.2 6.6-.1 1.06-.5 2.4-1.2 3.4 1.5-.1 3.1-.7 4.2-1.4 1.2.4 2.5.6 3.8.6 5.52 0 10-4.03 10-9S17.52 2 12 2z"/></svg>
        <span>${this.titleText()}</span>
      </button>
      <div class="kamea-widget">
        <div class="header"><span>${this.titleText()}</span><button class="close" aria-label="R\xE9duire">\u2715</button></div>
        <div class="messages"></div>
        ${this.consentGiven?this.inputRowHtml():this.consentHtml()}
      </div>
    `,this.messagesEl=e.querySelector(".messages"),this.panelEl=e.querySelector(".kamea-widget"),this.launcherEl=e.querySelector(".launcher"),this.launcherEl.addEventListener("click",()=>this.toggleOpen(!0)),e.querySelector(".close").addEventListener("click",()=>this.toggleOpen(!1)),this.applyOpenState(),this.consentGiven?(this.addMessage("assistant",this.greetingText()),this.bindInput(e)):e.querySelector(".consent button").addEventListener("click",()=>{this.consentGiven=!0,localStorage.setItem("kamea_advisor_consent","1"),this.render()})}toggleOpen(e){this.isOpen=e,localStorage.setItem("kamea_advisor_open",e?"1":"0"),this.applyOpenState()}applyOpenState(){this.panelEl.style.display=this.isOpen?"flex":"none",this.launcherEl.style.display=this.isOpen?"none":"flex"}consentHtml(){return`<div class="consent">${this.t("consent")}<br/><button>${this.t("accept")}</button></div>`}inputRowHtml(){return`
      <div class="phone-hint">${this.t("phoneHint")}</div>
      <div class="input-row">
        <input type="text" placeholder="${this.t("placeholder")}" />
        <button>${this.t("send")}</button>
      </div>
    `}setAwaitingPhone(e){this.shadow.querySelector(".input-row")?.classList.toggle("awaiting-phone",e);let t=this.shadow.querySelector(".phone-hint");t&&(t.style.display=e?"block":"none"),this.inputEl&&(this.inputEl.placeholder=e?this.t("phonePlaceholder"):this.t("placeholder"),this.inputEl.type=e?"tel":"text")}bindInput(e){this.inputEl=e.querySelector("input");let i=e.querySelector(".input-row button"),t=()=>{let n=this.inputEl.value.trim();n&&(this.inputEl.value="",this.handleSend(n))};i.addEventListener("click",t),this.inputEl.addEventListener("keydown",n=>{n.key==="Enter"&&t()})}addMessage(e,i){let t=document.createElement("div");return t.className=`msg ${e}`,t.textContent=i,this.messagesEl.appendChild(t),this.messagesEl.scrollTop=this.messagesEl.scrollHeight,t}async handleSend(e){this.addMessage("user",e);let i=this.addMessage("assistant",""),t="";await C(this.apiUrl,this.apiKey,this.tenantSlug,this.sessionId,e,{onToken:n=>{t+=n,i.textContent=t,this.messagesEl.scrollTop=this.messagesEl.scrollHeight},onHandoff:(n,r)=>{i.textContent=n,this.setAwaitingPhone(r)},onProducts:n=>{if(n.length===0)return;let r=document.createElement("div");r.className="products";for(let d of n)r.appendChild(this.renderProductCard(d));this.messagesEl.appendChild(r),this.messagesEl.scrollTop=this.messagesEl.scrollHeight},onError:n=>{i.textContent=n}})}renderProductCard(e){let i=document.createElement("div");i.className="product-card",i.innerHTML=`<strong>${e.title}</strong><br/>${e.price} \u20AC<br/><button>${this.t("addToCart")}</button>`;let t=i.querySelector("button");return t.addEventListener("click",async()=>{t.textContent="...";try{let d=(await(await fetch(`/products/${e.handle}.js`)).json()).variants[0].id;await fetch("/cart/add.js",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:[{id:d,quantity:1}]})}),t.textContent=this.t("added")}catch{t.textContent=this.t("addToCart")}}),i}};customElements.define("kamea-advisor",h);})();
